// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: service/rec.proto

package service

import (
	dao "a/b/c/dao"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *dao.Production        `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecRequest) Reset() {
	*x = RecRequest{}
	mi := &file_service_rec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecRequest) ProtoMessage() {}

func (x *RecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_rec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecRequest.ProtoReflect.Descriptor instead.
func (*RecRequest) Descriptor() ([]byte, []int) {
	return file_service_rec_proto_rawDescGZIP(), []int{0}
}

func (x *RecRequest) GetReq() *dao.Production {
	if x != nil {
		return x.Req
	}
	return nil
}

type RecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []int64                `protobuf:"varint,1,rep,packed,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecResponse) Reset() {
	*x = RecResponse{}
	mi := &file_service_rec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecResponse) ProtoMessage() {}

func (x *RecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_rec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecResponse.ProtoReflect.Descriptor instead.
func (*RecResponse) Descriptor() ([]byte, []int) {
	return file_service_rec_proto_rawDescGZIP(), []int{1}
}

func (x *RecResponse) GetResults() []int64 {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_service_rec_proto protoreflect.FileDescriptor

var file_service_rec_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x1a, 0x11, 0x64, 0x61, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x0c, 0x72, 0x65, 0x63,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x32, 0x42, 0x0a, 0x03, 0x72, 0x65, 0x63, 0x12, 0x3b, 0x0a, 0x04, 0x68, 0x6f,
	0x6d, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x72, 0x65, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x63, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_service_rec_proto_rawDescOnce sync.Once
	file_service_rec_proto_rawDescData []byte
)

func file_service_rec_proto_rawDescGZIP() []byte {
	file_service_rec_proto_rawDescOnce.Do(func() {
		file_service_rec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_rec_proto_rawDesc), len(file_service_rec_proto_rawDesc)))
	})
	return file_service_rec_proto_rawDescData
}

var file_service_rec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_rec_proto_goTypes = []any{
	(*RecRequest)(nil),     // 0: service.com.rec_request
	(*RecResponse)(nil),    // 1: service.com.rec_response
	(*dao.Production)(nil), // 2: dao.com.production
}
var file_service_rec_proto_depIdxs = []int32{
	2, // 0: service.com.rec_request.req:type_name -> dao.com.production
	0, // 1: service.com.rec.home:input_type -> service.com.rec_request
	1, // 2: service.com.rec.home:output_type -> service.com.rec_response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_rec_proto_init() }
func file_service_rec_proto_init() {
	if File_service_rec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_rec_proto_rawDesc), len(file_service_rec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_rec_proto_goTypes,
		DependencyIndexes: file_service_rec_proto_depIdxs,
		MessageInfos:      file_service_rec_proto_msgTypes,
	}.Build()
	File_service_rec_proto = out.File
	file_service_rec_proto_goTypes = nil
	file_service_rec_proto_depIdxs = nil
}
