// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: service/rec.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rec_Home_FullMethodName = "/service.com.rec/home"
)

// RecClient is the client API for Rec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecClient interface {
	Home(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error)
}

type recClient struct {
	cc grpc.ClientConnInterface
}

func NewRecClient(cc grpc.ClientConnInterface) RecClient {
	return &recClient{cc}
}

func (c *recClient) Home(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecResponse)
	err := c.cc.Invoke(ctx, Rec_Home_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecServer is the server API for Rec service.
// All implementations must embed UnimplementedRecServer
// for forward compatibility.
type RecServer interface {
	Home(context.Context, *RecRequest) (*RecResponse, error)
	mustEmbedUnimplementedRecServer()
}

// UnimplementedRecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecServer struct{}

func (UnimplementedRecServer) Home(context.Context, *RecRequest) (*RecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Home not implemented")
}
func (UnimplementedRecServer) mustEmbedUnimplementedRecServer() {}
func (UnimplementedRecServer) testEmbeddedByValue()             {}

// UnsafeRecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecServer will
// result in compilation errors.
type UnsafeRecServer interface {
	mustEmbedUnimplementedRecServer()
}

func RegisterRecServer(s grpc.ServiceRegistrar, srv RecServer) {
	// If the following call pancis, it indicates UnimplementedRecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rec_ServiceDesc, srv)
}

func _Rec_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rec_Home_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecServer).Home(ctx, req.(*RecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rec_ServiceDesc is the grpc.ServiceDesc for Rec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.com.rec",
	HandlerType: (*RecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "home",
			Handler:    _Rec_Home_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/rec.proto",
}
