// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: dao/product.proto

package dao

import (
	model "a/b/c/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Production struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Productor     *model.User            `protobuf:"bytes,1,opt,name=productor,proto3" json:"productor,omitempty"` // user前面需要加上它的package名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Production) Reset() {
	*x = Production{}
	mi := &file_dao_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Production) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Production) ProtoMessage() {}

func (x *Production) ProtoReflect() protoreflect.Message {
	mi := &file_dao_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Production.ProtoReflect.Descriptor instead.
func (*Production) Descriptor() ([]byte, []int) {
	return file_dao_product_proto_rawDescGZIP(), []int{0}
}

func (x *Production) GetProductor() *model.User {
	if x != nil {
		return x.Productor
	}
	return nil
}

var File_dao_product_proto protoreflect.FileDescriptor

var file_dao_product_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x64, 0x61, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x1a, 0x10, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x10, 0x5a, 0x0e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x64, 0x61, 0x6f, 0x3b, 0x64, 0x61, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_dao_product_proto_rawDescOnce sync.Once
	file_dao_product_proto_rawDescData []byte
)

func file_dao_product_proto_rawDescGZIP() []byte {
	file_dao_product_proto_rawDescOnce.Do(func() {
		file_dao_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dao_product_proto_rawDesc), len(file_dao_product_proto_rawDesc)))
	})
	return file_dao_product_proto_rawDescData
}

var file_dao_product_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dao_product_proto_goTypes = []any{
	(*Production)(nil), // 0: dao.com.production
	(*model.User)(nil), // 1: model.com.user
}
var file_dao_product_proto_depIdxs = []int32{
	1, // 0: dao.com.production.productor:type_name -> model.com.user
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dao_product_proto_init() }
func file_dao_product_proto_init() {
	if File_dao_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dao_product_proto_rawDesc), len(file_dao_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dao_product_proto_goTypes,
		DependencyIndexes: file_dao_product_proto_depIdxs,
		MessageInfos:      file_dao_product_proto_msgTypes,
	}.Build()
	File_dao_product_proto = out.File
	file_dao_product_proto_goTypes = nil
	file_dao_product_proto_depIdxs = nil
}
